### PR TITLE
Add Antidebug

### PR DESCRIPTION
**Pull request by vovanre**

### CODE REVIEW

**Comment by CrackFileso** [comment]
ez to bypass.

**Comment by vovanre** [comment]
> 
> 
> ez to bypass.

This is true, but there are no other ways to detect the debugger in Java (except for the native modules)

**Comment by ninng** [comment]
> ez to bypass.

But your FakeTryCatch is also ez to remove lol

你自己的 FakeTryCatch 还不是一样轻松删掉，还说别人

**Comment by ItzSomebody** [comment]
@vovanre Sorry for not getting back to you about your two PRs. I've been forgetting.

Hopefully sometime soon, I will be pushing a 2.0.0 release of Radon's codebase which is not backward-compatible with any previous versions whatsoever. When that time comes, would you mind adding a few more commits to get your transformer working in 2.0.0?

Thanks.

P.S. The 2.0.0 branch is not what the actual 2.0.0 release will actually look like.

**Comment by vovanre** [comment]
No problem. I'll update when the second version comes out.


P.S. Could you use the [lombok](https://projectlombok.org/) library? (for getters, setters and other)

**Comment by ItzSomebody** [comment]
I've actually been considering about using lombok since the release of 1.0.1 but haven't really given much thought to it. I'll ponder upon it relatively soon and we'll see in the future if I end up putting it in this project.

**Comment by Col-E** [comment]
> I've actually been considering about using lombok since the release of 1.0.1 but haven't really given much thought to it. 

Personally I only use Lombok on projects I have no intention of having others contribute on. I don't expect most programmers to have compliant workspaces _(or even understand whats going on. Lombok is kinda niche as far as I know)_. For example, its not supported by Eclipse by default so that would immediately throw lots of people off. IntelliJ recognizes it easily but not everyone uses IntelliJ.

**Comment by Eyremba** [comment]
> For example, its not supported by Eclipse by default

You can easily install it in Eclipse...

**Comment by Col-E** [comment]
> You can easily install it in Eclipse...

I agree. I have it added. But not everyone else will agree.

**Comment by ItzSomebody** [comment]
For context as to why this is being closed, see [this](https://github.com/ItzSomebody/Radon/pull/65#issuecomment-473759925)

**Pull request closed without merging**
