### PR TITLE
Add unit tests for me.itzsomebody.radon.utils.ASMUtils

### PR DESCRIPTION
**Pull request by JohnLBergqvist**
I've analysed your codebase and noticed that `me.itzsomebody.radon.utils.ASMUtils` is not fully tested.
I've written some tests for the methods in this class with the help of [Diffblue Cover](https://www.diffblue.com/opensource).

Hopefully, these tests will help you detect any regressions caused by future code changes. If you would find it useful to have additional tests written for this repository, I would be more than happy to look at other classes that you consider important.

### CODE REVIEW

**Comment by Col-E** [comment]
For the sake of clarity the opcode constants should probably reference ASM's Opcodes utility class instead of being magic numbers.

**Comment by JohnLBergqvist** [comment]
@Col-E I've addressed those changes

**Comment by Col-E** [comment]
There's some over-zealous usage now.

Cases like `(new InsnNode(Opcodes.NOP)` are _correct_ since the constructor parameter is the instruction's opcode. 

Cases like `new LdcInsnNode((float)Opcodes.NOP)` are _not correct_ since the constructor parameter is a value, not the instruction's opcode.

**Comment by JohnLBergqvist** [comment]
@Col-E Fixed.

**Pull request merged**
