### PR TITLE
Utf8 string too large fix

### PR DESCRIPTION
**Pull request by vovanre**
Fix for #45 issue.

### CODE REVIEW

**Comment by ItzSomebody** [comment]
Can't you just do
```java
if (str.getBytes(StandardCharsets.UTF_8).length > 65535) {/* stuff */}
```
?

**Comment by vovanre** [comment]
Can. But is it worth wasting memory to copy an array?

**Comment by ItzSomebody** [comment]
I don't really know. Less boilerplate is all I can say.

**Comment by vovanre** [comment]
```java
 private static InsnList getSafeStringInsnList(String string) {
        InsnList insnList = new InsnList();
        if (string.getBytes(StandardCharsets.UTF_8).length < StringUtils.MAX_SAFE_BYTE_COUNT) {
            insnList.add(new LdcInsnNode(string));
            return insnList;
        }

        insnList.add(new TypeInsnNode(NEW, "java/lang/StringBuilder"));
        insnList.add(new InsnNode(DUP));
        insnList.add(new MethodInsnNode(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false));

        String[] chunks = StringUtils.splitUtf8ToChunks(string, StringUtils.MAX_SAFE_BYTE_COUNT);
        for (String chunk : chunks) {
            insnList.add(new LdcInsnNode(chunk));
            insnList.add(new MethodInsnNode(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false));
        }
        insnList.add(new MethodInsnNode(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false));

        return insnList;
    }
```

Like that?

**Pull request closed without merging**
